options(warn=-1)
library(data.table)

## Missense, MAF > 0.1
AEN <- fread("results/AEN-maf-0.1.frq")
names(AEN) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CEM <- fread("results/CEM-maf-0.1.frq")
names(CEM) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
STP <- fread("results/STP-maf-0.1.frq")
names(STP) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CLB <- fread("results/CLB-maf-0.1.frq")
names(CLB) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
freqs <- data.table(AEN$MIN_FREQ, CEM$MIN_FREQ, STP$MIN_FREQ, CLB$MIN_FREQ)
nchr <- data.table(AEN$N_CHR, CEM$N_CHR, STP$N_CHR, CLB$N_CHR)
derived <- round(freqs * nchr)
#write.table(freqs, "results/ancient.freqs-maf-0.1.csv", sep=",", col.names=F, row.names=F)
write.table(nchr, "results/ancient.nchr-maf-0.1.csv", sep=",", col.names=F, row.names=F)
write.table(derived, "results/ancient.derived-maf-0.1.csv", sep=",", col.names=F, row.names=F)


## Missense, MAF < 0.1
AEN <- fread("results/AEN-maf-lt-0.1.frq")
names(AEN) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CEM <- fread("results/CEM-maf-lt-0.1.frq")
names(CEM) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
STP <- fread("results/STP-maf-lt-0.1.frq")
names(STP) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CLB <- fread("results/CLB-maf-lt-0.1.frq")
names(CLB) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
freqs <- data.table(AEN$MIN_FREQ, CEM$MIN_FREQ, STP$MIN_FREQ, CLB$MIN_FREQ)
nchr <- data.table(AEN$N_CHR, CEM$N_CHR, STP$N_CHR, CLB$N_CHR)
derived <- round(freqs * nchr)
#write.table(freqs, "results/ancient.freqs-maf-lt-0.1.csv", sep=",", col.names=F, row.names=F)
write.table(nchr, "results/ancient.nchr-maf-lt-0.1.csv", sep=",", col.names=F, row.names=F)
write.table(derived, "results/ancient.derived-maf-lt-0.1.csv", sep=",", col.names=F, row.names=F)

## Synonymous
AEN <- fread("results/AEN-syn.frq")
names(AEN) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CEM <- fread("results/CEM-syn.frq")
names(CEM) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
STP <- fread("results/STP-syn.frq")
names(STP) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
CLB <- fread("results/CLB-syn.frq")
names(CLB) <- c("CHROM", "POS", "N_ALLELES", "N_CHR", "MAJ_FREQ", "MIN_FREQ")
freqs <- data.table(AEN$MIN_FREQ, CEM$MIN_FREQ, STP$MIN_FREQ, CLB$MIN_FREQ)
nchr <- data.table(AEN$N_CHR, CEM$N_CHR, STP$N_CHR, CLB$N_CHR)
derived <- round(freqs * nchr)
#write.table(freqs, "results/ancient.freqs-syn.csv", sep=",", col.names=F, row.names=F)
write.table(nchr, "results/ancient.nchr-syn.csv", sep=",", col.names=F, row.names=F)
write.table(derived, "results/ancient.derived-syn.csv", sep=",", col.names=F, row.names=F)